/**
 * ShortKey Studio v0.1 — seed defaults (in-memory + first file write).
 * Domain map carried from Studio P0 DNA Control Room.
 */

import {
  createSeedHallyuFormula,
  HALLYU_SEED_CAMPAIGN_ID,
} from "@/lib/studio/hallyuFormula";
import { createSeedIdentityBenchmark } from "@/lib/studio/brandIdentityLanes";
import type { StudioState } from "@/lib/studio/types";

const now = "2026-07-24T00:00:00.000Z";
const hallyuNow = "2026-07-25T00:00:00.000Z";

export function createStudioSeed(): StudioState {
  return {
    version: "0.1",
    brandDna: {
      id: "dna_shortkey_v01",
      label: "ShortKey Brand DNA",
      tagline: "One DNA. Many doors.",
      points: [
        "Creator-first, brand-ready",
        "Asian beauty bridge",
        "Link-based promotion first",
        "ROI reporting is the value",
        "Simple transparent packages",
        "Trust and protection",
        "Premium editorial beauty",
        "Internal logic stays internal",
      ],
      copyBlocks: [
        {
          label: "Brand line",
          text: "ShortKey helps Asian beauty brands enter new markets through creator discovery, trackable campaigns, and clear performance reporting.",
        },
        {
          label: "Creator line",
          text: "ShortKey helps beauty creators become discoverable to brands looking for authentic product storytelling.",
        },
        {
          label: "Safety line",
          text: "Registration does not guarantee selection, paid campaigns, income, or sales results.",
        },
        {
          label: "Value line",
          text: "ShortKey is built around clarity: approved assets, link-based promotion, objective completion, and measurable reporting.",
        },
      ],
      buildOrder: [
        "Studio P0 → Studio v0.1",
        "Social P0",
        "Beauty polish",
        "Info brand page",
        "Live later",
        "World future",
      ],
      status: "APPROVED",
      updatedAt: now,
    },
    domains: [
      {
        id: "dom_studio",
        hostname: "shortkey.studio",
        purpose: "Internal DNA, assets, control room",
        status: "APPROVED",
        notes: "This surface · Studio control center",
        updatedAt: now,
      },
      {
        id: "dom_social",
        hostname: "shortkey.social",
        purpose: "Creator Early Access and waitlist",
        status: "GOR_GOR_REVIEW",
        notes: "Staging portal at /social · port 3004 · not production · no Deploy Center publish",
        updatedAt: now,
      },
      {
        id: "dom_beauty",
        hostname: "shortkey.beauty",
        purpose: "Main public beauty entrance",
        status: "IN_REVIEW",
        notes: "Coming Soon public page stays separate — do not edit from Studio publish.",
        updatedAt: now,
      },
      {
        id: "dom_live",
        hostname: "shortkey.live",
        purpose: "Future live layer, not main priority",
        status: "ARCHIVED",
        notes: "FROZEN — records only",
        updatedAt: now,
      },
      {
        id: "dom_info",
        hostname: "shortkey.info",
        purpose: "Brand information and onboarding",
        status: "DRAFT",
        notes: "",
        updatedAt: now,
      },
      {
        id: "dom_world",
        hostname: "shortkey.world",
        purpose: "Global expansion future layer",
        status: "DRAFT",
        notes: "",
        updatedAt: now,
      },
      {
        id: "dom_store",
        hostname: "shortkey.store",
        purpose: "Consumer product discovery later",
        status: "DRAFT",
        notes: "",
        updatedAt: now,
      },
      {
        id: "dom_family",
        hostname: "family.shortkey.world",
        purpose: "Internal AI Family Home only",
        status: "APPROVED",
        notes: "Family Table / doorbell — separate surface :3002",
        updatedAt: now,
      },
    ],
    countries: [
      {
        id: "cty_jp",
        code: "JP",
        label: "Japan",
        localeHint: "ja-JP",
        status: "DRAFT",
        notes: "Placeholder registry row",
        updatedAt: now,
      },
      {
        id: "cty_kr",
        code: "KR",
        label: "Korea",
        localeHint: "ko-KR",
        status: "DRAFT",
        notes: "Placeholder registry row",
        updatedAt: now,
      },
      {
        id: "cty_twhk",
        code: "TW-HK",
        label: "Taiwan / Hong Kong (繁)",
        localeHint: "zh-Hant",
        status: "DRAFT",
        notes: "繁中 placeholder",
        updatedAt: now,
      },
      {
        id: "cty_global",
        code: "GLOBAL",
        label: "Global",
        localeHint: "en",
        status: "DRAFT",
        notes: "Fallback / multi-market placeholder",
        updatedAt: now,
      },
    ],
    assets: [
      {
        id: "ast_brand_line",
        name: "Approved Brand Line (copy)",
        kind: "copy",
        domainIds: ["dom_beauty", "dom_info", "dom_studio"],
        status: "GOR_GOR_REVIEW",
        notes: "Metadata only — no binary upload in v0.1",
        updatedAt: now,
      },
      {
        id: "ast_creator_line",
        name: "Approved Creator Line (copy)",
        kind: "copy",
        domainIds: ["dom_social", "dom_beauty"],
        status: "KIERAN_REVIEW_READY",
        notes: "Metadata only",
        updatedAt: now,
      },
      {
        id: "ast_safety_line",
        name: "Safety / disclaimer line",
        kind: "copy",
        domainIds: ["dom_beauty", "dom_social", "dom_info"],
        status: "APPROVED",
        notes: "Must ship with any public registration surface",
        updatedAt: now,
      },
      {
        id: "ast_hero_placeholder",
        name: "Beauty hero visual (placeholder metadata)",
        kind: "image",
        domainIds: ["dom_beauty"],
        status: "DRAFT",
        notes: "Asset Library stores metadata only in v0.1",
        updatedAt: now,
      },
    ],
    campaigns: [
      {
        id: "cmp_founding_wave",
        name: "Founding Wave — Aug 14, 2026",
        domainIds: ["dom_beauty", "dom_social"],
        countryIds: ["cty_global", "cty_twhk"],
        assetIds: ["ast_brand_line", "ast_safety_line"],
        status: "GOR_GOR_REVIEW",
        notes: "Registry record only — no scheduler automation",
        updatedAt: now,
      },
      {
        id: "cmp_creator_early",
        name: "Creator Early Access (Social)",
        domainIds: ["dom_social"],
        countryIds: ["cty_global"],
        assetIds: ["ast_creator_line", "ast_safety_line"],
        status: "KIERAN_REVIEW_READY",
        notes: "",
        updatedAt: now,
      },
      {
        id: HALLYU_SEED_CAMPAIGN_ID,
        name: "Hallyu → Creator Formula (Product Story Readiness)",
        domainIds: ["dom_studio", "dom_social"],
        countryIds: ["cty_global", "cty_jp", "cty_kr", "cty_twhk"],
        assetIds: ["ast_brand_line", "ast_creator_line", "ast_safety_line"],
        status: "GOR_GOR_REVIEW",
        notes:
          "Educational campaign card · Historical K-beauty pattern vs ShortKey Creator formula · no celeb/brand scrapes · staging only",
        updatedAt: hallyuNow,
        hallyuFormula: createSeedHallyuFormula(),
      },
    ],
    deploymentPlans: [
      {
        id: "dep_studio_v01_record",
        title: "Studio v0.1 internal staging (records only)",
        domainIds: ["dom_studio"],
        campaignIds: [],
        scheduledFor: null,
        status: "APPROVED",
        notes: "No Vercel publish from this plan. Records + status only.",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "dep_beauty_placeholder",
        title: "Beauty Coming Soon — do not auto-deploy",
        domainIds: ["dom_beauty"],
        campaignIds: ["cmp_founding_wave"],
        scheduledFor: "2026-08-14T00:00:00.000Z",
        status: "SCHEDULED",
        notes: "Placeholder schedule date. Studio does not call production deploy APIs.",
        createdAt: now,
        updatedAt: now,
      },
    ],
    rollbackRefs: [
      {
        id: "rb_studio_p0_dna",
        title: "Rollback ref · Studio P0 DNA Control Room baseline",
        snapshotId: null,
        domainIds: ["dom_studio"],
        status: "ROLLBACK_READY",
        notes: "Reference only — predecessor static DNA Control Room. No automated rollback.",
        createdAt: now,
      },
    ],
    approvalLogs: [
      {
        id: "log_seed_dna",
        entityType: "brandDna",
        entityId: "dna_shortkey_v01",
        entityLabel: "ShortKey Brand DNA",
        who: "Kieran",
        when: now,
        fromStatus: "DRAFT",
        toStatus: "APPROVED",
        note: "Seed: carried from Studio P0 DNA Control Room into Studio v0.1",
      },
      {
        id: "log_seed_identity",
        entityType: "identityBenchmark",
        entityId: "identity_benchmark_v01",
        entityLabel: "Brand Identity Benchmark Map",
        who: "Gor Gor",
        when: hallyuNow,
        fromStatus: "DRAFT",
        toStatus: "GOR_GOR_REVIEW",
        note: "Seed: J/K/C identity lanes + Preview archetypes — no brand scrapes",
      },
    ],
    identityBenchmark: createSeedIdentityBenchmark(),
    versionSnapshots: [],
  };
}
