import { productImg } from "@/lib/images";

export type ShopCategory = "Makeup" | "Skin Care";
export type ShopRegion = "K-Beauty" | "J-Beauty" | "C-Beauty" | "Multi";

/** Canonical shop records — source of truth for /shop prices & filters */
export type ShopProductRecord = {
  sku: string;
  name: string;
  type: string;
  category: ShopCategory;
  region: ShopRegion;
  priceUsd: number;
  image: string;
  /** Marked true when ready to push / already mapped for Shopify */
  syncReady: boolean;
  description?: string;
};

/**
 * First sync batch: all unique makeup SKUs + a short skincare starter set.
 * Fill sku-map.ts after creating matching Shopify variants.
 */
export const shopCatalog: ShopProductRecord[] = [
  // —— Makeup (sync-ready first wave) ——
  {
    sku: "SK-M001",
    name: "Glass Lip Gloss",
    type: "High-Shine Gloss",
    category: "Makeup",
    region: "K-Beauty",
    priceUsd: 18,
    image: productImg("SK-M001"),
    syncReady: true,
    description: "Mirror finish gloss for glass-skin pouts.",
  },
  {
    sku: "SK-M002",
    name: "Velvet Lip Plump",
    type: "Plumping Balm",
    category: "Makeup",
    region: "K-Beauty",
    priceUsd: 20,
    image: productImg("SK-M002"),
    syncReady: true,
  },
  {
    sku: "SK-M003",
    name: "Rose Oil Lip Tint",
    type: "Tinted Lip Oil",
    category: "Makeup",
    region: "K-Beauty",
    priceUsd: 22,
    image: productImg("SK-M003"),
    syncReady: true,
    description: "Hero shade for influencer try-on streams.",
  },
  {
    sku: "SK-M004",
    name: "Precision Felt Liner",
    type: "Liquid Eyeliner",
    category: "Makeup",
    region: "J-Beauty",
    priceUsd: 16,
    image: productImg("SK-M004"),
    syncReady: true,
  },
  {
    sku: "SK-M005",
    name: "Cat Eye Stamp Pen",
    type: "Wing Template",
    category: "Makeup",
    region: "J-Beauty",
    priceUsd: 19,
    image: productImg("SK-M005"),
    syncReady: true,
  },
  {
    sku: "SK-M006",
    name: "Smudge-Proof Gel Liner",
    type: "Waterproof Liner",
    category: "Makeup",
    region: "J-Beauty",
    priceUsd: 17,
    image: productImg("SK-M006"),
    syncReady: true,
  },
  {
    sku: "SK-M007",
    name: "Soft Sculpt Palette",
    type: "Contour Kit",
    category: "Makeup",
    region: "K-Beauty",
    priceUsd: 34,
    image: productImg("SK-M007"),
    syncReady: true,
  },
  {
    sku: "SK-M008",
    name: "Cream Contour Stick",
    type: "Face Sculpt",
    category: "Makeup",
    region: "K-Beauty",
    priceUsd: 24,
    image: productImg("SK-M008"),
    syncReady: true,
  },
  {
    sku: "SK-M009",
    name: "Champagne Highlight",
    type: "Liquid Highlight",
    category: "Makeup",
    region: "Multi",
    priceUsd: 26,
    image: productImg("SK-M009"),
    syncReady: true,
  },
  {
    sku: "SK-M010",
    name: "Skin Fit Cushion",
    type: "Foundation Cushion",
    category: "Makeup",
    region: "K-Beauty",
    priceUsd: 38,
    image: productImg("SK-M010"),
    syncReady: true,
  },
  {
    sku: "SK-M011",
    name: "Seamless Concealer",
    type: "Full Cover Concealer",
    category: "Makeup",
    region: "K-Beauty",
    priceUsd: 28,
    image: productImg("SK-M011"),
    syncReady: true,
  },
  {
    sku: "SK-M012",
    name: "Blur Primer Base",
    type: "Pore-Blur Primer",
    category: "Makeup",
    region: "C-Beauty",
    priceUsd: 27,
    image: productImg("SK-M012"),
    syncReady: true,
  },
  {
    sku: "SK-M013",
    name: "Cherry Lip Cheek Tint",
    type: "Multi-Use Tint",
    category: "Makeup",
    region: "K-Beauty",
    priceUsd: 21,
    image: productImg("SK-M013"),
    syncReady: true,
  },
  {
    sku: "SK-M014",
    name: "Berry Water Tint",
    type: "Sheer Lip Tint",
    category: "Makeup",
    region: "J-Beauty",
    priceUsd: 19,
    image: productImg("SK-M014"),
    syncReady: true,
  },
  {
    sku: "SK-M015",
    name: "Peach Flush Stick",
    type: "Cream Blush Tint",
    category: "Makeup",
    region: "K-Beauty",
    priceUsd: 23,
    image: productImg("SK-M015"),
    syncReady: true,
  },
  {
    sku: "SK-M016",
    name: "Cloud Setting Powder",
    type: "Translucent Powder",
    category: "Makeup",
    region: "C-Beauty",
    priceUsd: 29,
    image: productImg("SK-M016"),
    syncReady: true,
  },
  {
    sku: "SK-M017",
    name: "Dew Fix Mist",
    type: "Setting Spray",
    category: "Makeup",
    region: "J-Beauty",
    priceUsd: 25,
    image: productImg("SK-M017"),
    syncReady: true,
  },
  {
    sku: "SK-M018",
    name: "Soft Focus Filter Balm",
    type: "Blurring Finish",
    category: "Makeup",
    region: "Multi",
    priceUsd: 30,
    image: productImg("SK-M018"),
    syncReady: true,
  },

  // —— Skin Care starter set (sync next wave) ——
  {
    sku: "SK-Z001",
    name: "Daily Soft SPF",
    type: "Lightweight Sunscreen",
    category: "Skin Care",
    region: "K-Beauty",
    priceUsd: 32,
    image: productImg("SK-Z001"),
    syncReady: true,
  },
  {
    sku: "SK-Z002",
    name: "Tone-Up Sun Fluid",
    type: "UV Tone Protector",
    category: "Skin Care",
    region: "K-Beauty",
    priceUsd: 34,
    image: productImg("SK-Z002"),
    syncReady: false,
  },
  {
    sku: "SK-B001",
    name: "Bright Barrier Cream",
    type: "SPF Moisturizer",
    category: "Skin Care",
    region: "C-Beauty",
    priceUsd: 36,
    image: productImg("SK-B001"),
    syncReady: true,
  },
  {
    sku: "SK-B002",
    name: "Dew Boost Lotion",
    type: "Hydrating Lotion",
    category: "Skin Care",
    region: "C-Beauty",
    priceUsd: 28,
    image: productImg("SK-B002"),
    syncReady: false,
  },
  {
    sku: "SK-B003",
    name: "Layering Softener",
    type: "Skin Softener",
    category: "Skin Care",
    region: "C-Beauty",
    priceUsd: 26,
    image: productImg("SK-B003"),
    syncReady: false,
  },
  {
    sku: "SK-H001",
    name: "Hydra Sun Gel",
    type: "Watery SPF",
    category: "Skin Care",
    region: "J-Beauty",
    priceUsd: 30,
    image: productImg("SK-H001"),
    syncReady: true,
  },
  {
    sku: "SK-H002",
    name: "Water Bank Gel",
    type: "Gel Cream",
    category: "Skin Care",
    region: "J-Beauty",
    priceUsd: 33,
    image: productImg("SK-H002"),
    syncReady: false,
  },
  {
    sku: "SK-H003",
    name: "Ceramide Lock Balm",
    type: "Barrier Balm",
    category: "Skin Care",
    region: "J-Beauty",
    priceUsd: 35,
    image: productImg("SK-H003"),
    syncReady: false,
  },
  {
    sku: "SK-G001",
    name: "Glow Guard Mist",
    type: "Setting SPF Mist",
    category: "Skin Care",
    region: "K-Beauty",
    priceUsd: 27,
    image: productImg("SK-G001"),
    syncReady: true,
  },
  {
    sku: "SK-G002",
    name: "Glass Skin Cream",
    type: "Illuminating Moisturizer",
    category: "Skin Care",
    region: "K-Beauty",
    priceUsd: 39,
    image: productImg("SK-G002"),
    syncReady: false,
  },
  {
    sku: "SK-G003",
    name: "Glass Drop Concentrate",
    type: "Radiance Ampoule",
    category: "Skin Care",
    region: "K-Beauty",
    priceUsd: 42,
    image: productImg("SK-G003"),
    syncReady: false,
  },
  {
    sku: "SK-D001",
    name: "Defense Day Cream",
    type: "Anti-Pollution SPF",
    category: "Skin Care",
    region: "Multi",
    priceUsd: 31,
    image: productImg("SK-D001"),
    syncReady: true,
  },
  {
    sku: "SK-D002",
    name: "Oil Melt Balm",
    type: "Cleansing Balm",
    category: "Skin Care",
    region: "Multi",
    priceUsd: 29,
    image: productImg("SK-D002"),
    syncReady: false,
  },
  {
    sku: "SK-D003",
    name: "Micellar Clear Water",
    type: "Micellar Water",
    category: "Skin Care",
    region: "Multi",
    priceUsd: 22,
    image: productImg("SK-D003"),
    syncReady: false,
  },
];

export function getShopCatalogRecord(sku: string): ShopProductRecord | undefined {
  const key = sku.toUpperCase();
  return shopCatalog.find((p) => p.sku.toUpperCase() === key);
}

export function getSyncReadyProducts(): ShopProductRecord[] {
  return shopCatalog.filter((p) => p.syncReady);
}
